version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:8001:8000
    networks:
      - saga_introduction_kafkanetwork
    volumes:
      - ${PWD}/src/app/db.sqlite3:/code/app/db.sqlite3

  redis:
    image: redis:alpine
    networks:
      - saga_introduction_kafkanetwork

networks:
  saga_introduction_kafkanetwork:
    external: true
